ISA_ROOT=/local/scratch/mpew2/Isabelle
ISA_ROOT=/cygdrive/e/Software/Isabelle


all:	docs


docs:
	$(ISA_ROOT)/Isabelle2020/bin/isabelle build -D . MiniSail


snippets:
	$(ISA_ROOT)/Isabelle2020/bin/isabelle build -D . Snippets

